AWSTemplateFormatVersion: 2010-09-09
Resources:
    UserDatabase:
        Type: 'AWS::DynamoDB::Table'
        Properties:
            AttributeDefinitions:
                - AttributeName: user
                  AttributeType: S
            BillingMode: PAY_PER_REQUEST
            KeySchema:
                - AttributeName: user
                  KeyType: HASH
            TableName: !Sub "jonet.users_db.${Env}"
            Tags:
                - Key: App
                  Value: JoNet
                - Key: Env
                  Value: !Ref Env
    SystemKey:
        Type: "AWS::SecretsManager::Secret"
        Properties:
            GenerateSecretString: {}
            Tags: 
                - Key: App
                  Value: JoNet
                - Key: Env
                  Value: !Ref Env
            Name: !Sub "jonet.system_key.${Env}"

Parameters:
    Env:
        Type: String

