AWSTemplateFormatVersion: 2010-09-09

Parameters: 
  AppName:
    Type: String
  AppTld:
    Type: String
  ServiceName:
    Type: String
  AliasTargetDnsName:
    Type: String
  AliasTargetHostedZoneId:
    Type: String
  ServiceEnv:
    Type: String

Conditions:
  IsProd: !Equals [!Ref ServiceEnv, master]

Resources:
  Dns:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !Ref AliasTargetDnsName
        HostedZoneId: !Ref AliasTargetHostedZoneId
      HostedZoneName: !Sub '${AppName}.${AppTld}.'
      Name:
        Fn::If:
          - IsProd
          - !Sub '${ServiceName}.${AppName}.${AppTld}'
          - !Sub '${ServiceEnv}.${ServiceName}.${AppName}.${AppTld}'
      Type: A

